export const imageList = [
  'https://i.imgur.com/E47CNTR.png',
  'https://i.imgur.com/YLj4mbo.png',
  'https://i.imgur.com/sd2hHww.png',
  'https://i.imgur.com/sd2hHww.png',
  'https://i.imgur.com/AzRw872.png',
  'https://i.imgur.com/PMsMBZ4.png',
  'https://i.imgur.com/G6k4t8t.png',
  'https://i.imgur.com/3yZfNIH.png',
  'https://i.imgur.com/LbqSZXs.png',
  'https://i.imgur.com/zJhFQ8A.png',
  'https://i.imgur.com/2edzOb4.png',
  'https://i.imgur.com/nmn9OCt.png',
  'https://i.imgur.com/BjLNZeH.png',
  'https://i.imgur.com/GffOigH.png',
  'https://i.imgur.com/H3PbAR3.png',
  'https://i.imgur.com/9LjZKeI.png',
];
