POST {{HTTP_HOST}}/auth/login
Accept: application/json
X-Test-Uid: {{ X_TEST_UID }}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

POST {{HTTP_HOST}}/auth/login
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 404, "Response status is not 404");
});
%}