import {MigrationInterface, QueryRunner} from "typeorm";

export class scratch1639242388214 implements MigrationInterface {
    name = 'scratch1639242388214'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."comment_rate_enum" AS ENUM('sieu-pham', 'co-tiem-nang', 'dang-tien', 'hay', 'cung-duoc', 'xam-xi')`);
        await queryRunner.query(`CREATE TABLE "comment" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "content" character varying NOT NULL, "rate" "public"."comment_rate_enum" array NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "authorUid" character varying(64), "showcaseId" integer, CONSTRAINT "PK_0b0e4bbc8415ec426f87f3a88e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."media_type_enum" AS ENUM('0', '1', '2')`);
        await queryRunner.query(`CREATE TABLE "media" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "filename" character varying NOT NULL, "path" character varying NOT NULL, "mimetype" character varying NOT NULL, "type" "public"."media_type_enum" NOT NULL, "showcaseId" integer, "hfId" integer, "listId" integer, CONSTRAINT "REL_3de002b2c50816776d2e11f0f1" UNIQUE ("showcaseId"), CONSTRAINT "REL_044aaee047a52bee8b69b3fd86" UNIQUE ("hfId"), CONSTRAINT "PK_f4e0fcac36e050de337b670d8bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_637a0dd7f9068a9ca80decee00" ON "media" ("type") `);
        await queryRunner.query(`CREATE TABLE "showcaseHighlightFeature" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, "showcaseId" integer, CONSTRAINT "PK_694ef0a8e2e001f603774d6b445" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "imageList" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "showcaseId" integer, CONSTRAINT "PK_79c804e1be18e8b55b58860266a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "investmentPackage" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "displayName" character varying NOT NULL, "fundedRate" integer NOT NULL, "count" integer NOT NULL, "benefitRate" integer NOT NULL, CONSTRAINT "PK_c9fa73aa838c64e4742289b3cce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."showcase_status_enum" AS ENUM('coming soon', 'idea', 'showcase')`);
        await queryRunner.query(`CREATE TYPE "public"."showcase_publishstatus_enum" AS ENUM('draft', 'published')`);
        await queryRunner.query(`CREATE TABLE "showcase" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "brand" jsonb NOT NULL, "status" "public"."showcase_status_enum" NOT NULL DEFAULT 'showcase', "publishStatus" "public"."showcase_publishstatus_enum" NOT NULL DEFAULT 'draft', "description" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "expectedSaleAt" date, "expectedSaleEndAt" date, "expectedQuantity" jsonb, "expectedSalePrice" jsonb, "inventory" jsonb, "authorUid" character varying(64), CONSTRAINT "PK_cacb526c9c1e4a9e9db58879955" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d64668230aa248cdad4474ab5c" ON "showcase" ("slug") `);
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum" AS ENUM('superadmin', 'admin', 'investor', 'user')`);
        await queryRunner.query(`CREATE TABLE "user" ("uid" character varying(64) NOT NULL, "name" character varying NOT NULL, "email" character varying NOT NULL, "role" "public"."user_role_enum" NOT NULL DEFAULT 'user', CONSTRAINT "PK_df955cae05f17b2bcf5045cc021" PRIMARY KEY ("uid"))`);
        await queryRunner.query(`CREATE TABLE "setting" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "key" character varying NOT NULL, "value" json NOT NULL, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1c4c95d773004250c157a744d6e" UNIQUE ("key"), CONSTRAINT "PK_fcb21187dc6094e24a48f677bed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1c4c95d773004250c157a744d6" ON "setting" ("key") `);
        await queryRunner.query(`CREATE TABLE "showcase_available_investment_packages_investment_package" ("showcaseId" integer NOT NULL, "investmentPackageId" integer NOT NULL, CONSTRAINT "PK_9482a3db81ba62906da849e7a29" PRIMARY KEY ("showcaseId", "investmentPackageId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ca71febec6924905bbd98dc4e5" ON "showcase_available_investment_packages_investment_package" ("showcaseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7ddb57477dd875359677c2e9c7" ON "showcase_available_investment_packages_investment_package" ("investmentPackageId") `);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_07b601722fecec8fde42d282ce6" FOREIGN KEY ("authorUid") REFERENCES "user"("uid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_922fe660999d621d42bf6bb49c7" FOREIGN KEY ("showcaseId") REFERENCES "showcase"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_3de002b2c50816776d2e11f0f14" FOREIGN KEY ("showcaseId") REFERENCES "showcase"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_044aaee047a52bee8b69b3fd867" FOREIGN KEY ("hfId") REFERENCES "showcaseHighlightFeature"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_89036447c82b522dc27296a1242" FOREIGN KEY ("listId") REFERENCES "imageList"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "showcaseHighlightFeature" ADD CONSTRAINT "FK_b3ed0a0cdefa5175c00a798e294" FOREIGN KEY ("showcaseId") REFERENCES "showcase"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "imageList" ADD CONSTRAINT "FK_77bf5000a94278ec58e9fcdf05c" FOREIGN KEY ("showcaseId") REFERENCES "showcase"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "showcase" ADD CONSTRAINT "FK_0d9e58c204ceb7b9e7c82353fa1" FOREIGN KEY ("authorUid") REFERENCES "user"("uid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "showcase_available_investment_packages_investment_package" ADD CONSTRAINT "FK_ca71febec6924905bbd98dc4e54" FOREIGN KEY ("showcaseId") REFERENCES "showcase"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "showcase_available_investment_packages_investment_package" ADD CONSTRAINT "FK_7ddb57477dd875359677c2e9c7a" FOREIGN KEY ("investmentPackageId") REFERENCES "investmentPackage"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "showcase_available_investment_packages_investment_package" DROP CONSTRAINT "FK_7ddb57477dd875359677c2e9c7a"`);
        await queryRunner.query(`ALTER TABLE "showcase_available_investment_packages_investment_package" DROP CONSTRAINT "FK_ca71febec6924905bbd98dc4e54"`);
        await queryRunner.query(`ALTER TABLE "showcase" DROP CONSTRAINT "FK_0d9e58c204ceb7b9e7c82353fa1"`);
        await queryRunner.query(`ALTER TABLE "imageList" DROP CONSTRAINT "FK_77bf5000a94278ec58e9fcdf05c"`);
        await queryRunner.query(`ALTER TABLE "showcaseHighlightFeature" DROP CONSTRAINT "FK_b3ed0a0cdefa5175c00a798e294"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_89036447c82b522dc27296a1242"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_044aaee047a52bee8b69b3fd867"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_3de002b2c50816776d2e11f0f14"`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_922fe660999d621d42bf6bb49c7"`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_07b601722fecec8fde42d282ce6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7ddb57477dd875359677c2e9c7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca71febec6924905bbd98dc4e5"`);
        await queryRunner.query(`DROP TABLE "showcase_available_investment_packages_investment_package"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1c4c95d773004250c157a744d6"`);
        await queryRunner.query(`DROP TABLE "setting"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d64668230aa248cdad4474ab5c"`);
        await queryRunner.query(`DROP TABLE "showcase"`);
        await queryRunner.query(`DROP TYPE "public"."showcase_publishstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."showcase_status_enum"`);
        await queryRunner.query(`DROP TABLE "investmentPackage"`);
        await queryRunner.query(`DROP TABLE "imageList"`);
        await queryRunner.query(`DROP TABLE "showcaseHighlightFeature"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_637a0dd7f9068a9ca80decee00"`);
        await queryRunner.query(`DROP TABLE "media"`);
        await queryRunner.query(`DROP TYPE "public"."media_type_enum"`);
        await queryRunner.query(`DROP TABLE "comment"`);
        await queryRunner.query(`DROP TYPE "public"."comment_rate_enum"`);
    }

}
