import {MigrationInterface, QueryRunner} from "typeorm";

export class fcmEntity1643571414862 implements MigrationInterface {
    name = 'fcmEntity1643571414862'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "fcm-registration-token" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "token" character varying NOT NULL, "topic" character varying NOT NULL, "authorUid" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7dd5bc4cd7e410805b674330821" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_27c4754ec6bdbf0102b2398f52" ON "fcm-registration-token" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_3f7846c4124c916aa1397613e6" ON "fcm-registration-token" ("topic") `);
        await queryRunner.query(`CREATE INDEX "IDX_5f2468757a1f52bc6f61e87dbc" ON "fcm-registration-token" ("authorUid") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_5f2468757a1f52bc6f61e87dbc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f7846c4124c916aa1397613e6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_27c4754ec6bdbf0102b2398f52"`);
        await queryRunner.query(`DROP TABLE "fcm-registration-token"`);
    }

}
