import { MigrationInterface, QueryRunner } from 'typeorm';

export class comment1638862152737 implements MigrationInterface {
  name = 'comment1638862152737';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TYPE "public"."comment_rate_enum" AS ENUM('sieu-pham', 'co-tiem-nang', 'dang-tien', 'hay', 'cung-duoc', 'xam-xi')`,
    );
    await queryRunner.query(
      `CREATE TABLE "comment" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "content" character varying NOT NULL, "rate" "public"."comment_rate_enum" array NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "authorUid" character varying(64), "showcaseId" integer, CONSTRAINT "PK_0b0e4bbc8415ec426f87f3a88e2" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `ALTER TABLE "comment" ADD CONSTRAINT "FK_07b601722fecec8fde42d282ce6" FOREIGN KEY ("authorUid") REFERENCES "user"("uid") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "comment" ADD CONSTRAINT "FK_922fe660999d621d42bf6bb49c7" FOREIGN KEY ("showcaseId") REFERENCES "showcase"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "comment" DROP CONSTRAINT "FK_922fe660999d621d42bf6bb49c7"`,
    );
    await queryRunner.query(
      `ALTER TABLE "comment" DROP CONSTRAINT "FK_07b601722fecec8fde42d282ce6"`,
    );
    await queryRunner.query(`DROP TABLE "comment"`);
    await queryRunner.query(`DROP TYPE "public"."comment_rate_enum"`);
  }
}
