import { MigrationInterface, QueryRunner } from 'typeorm';

export class extendShowcase1638617771017 implements MigrationInterface {
  name = 'extendShowcase1638617771017';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "investmentPackage" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "displayName" character varying NOT NULL, "fundedRate" integer NOT NULL, "count" integer NOT NULL, "benefitRate" integer NOT NULL, CONSTRAINT "PK_c9fa73aa838c64e4742289b3cce" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "showcase_available_investment_packages_investment_package" ("showcaseId" integer NOT NULL, "investmentPackageId" integer NOT NULL, CONSTRAINT "PK_9482a3db81ba62906da849e7a29" PRIMARY KEY ("showcaseId", "investmentPackageId"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_ca71febec6924905bbd98dc4e5" ON "showcase_available_investment_packages_investment_package" ("showcaseId") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_7ddb57477dd875359677c2e9c7" ON "showcase_available_investment_packages_investment_package" ("investmentPackageId") `,
    );
    await queryRunner.query(`ALTER TABLE "showcase" ADD "inventory" jsonb`);
    await queryRunner.query(
      `ALTER TABLE "showcase_available_investment_packages_investment_package" ADD CONSTRAINT "FK_ca71febec6924905bbd98dc4e54" FOREIGN KEY ("showcaseId") REFERENCES "showcase"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "showcase_available_investment_packages_investment_package" ADD CONSTRAINT "FK_7ddb57477dd875359677c2e9c7a" FOREIGN KEY ("investmentPackageId") REFERENCES "investmentPackage"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "showcase_available_investment_packages_investment_package" DROP CONSTRAINT "FK_7ddb57477dd875359677c2e9c7a"`,
    );
    await queryRunner.query(
      `ALTER TABLE "showcase_available_investment_packages_investment_package" DROP CONSTRAINT "FK_ca71febec6924905bbd98dc4e54"`,
    );
    await queryRunner.query(`ALTER TABLE "showcase" DROP COLUMN "inventory"`);
    await queryRunner.query(
      `DROP INDEX "public"."IDX_7ddb57477dd875359677c2e9c7"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_ca71febec6924905bbd98dc4e5"`,
    );
    await queryRunner.query(
      `DROP TABLE "showcase_available_investment_packages_investment_package"`,
    );
    await queryRunner.query(`DROP TABLE "investmentPackage"`);
  }
}
