import {MigrationInterface, QueryRunner} from "typeorm";

export class imagelist1638050471011 implements MigrationInterface {
    name = 'imagelist1638050471011'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "imageList" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "showcaseId" integer, CONSTRAINT "PK_79c804e1be18e8b55b58860266a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "media" ADD "listId" integer`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_89036447c82b522dc27296a1242" FOREIGN KEY ("listId") REFERENCES "imageList"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "imageList" ADD CONSTRAINT "FK_77bf5000a94278ec58e9fcdf05c" FOREIGN KEY ("showcaseId") REFERENCES "showcase"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "imageList" DROP CONSTRAINT "FK_77bf5000a94278ec58e9fcdf05c"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_89036447c82b522dc27296a1242"`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "listId"`);
        await queryRunner.query(`DROP TABLE "imageList"`);
    }

}
