import {MigrationInterface, QueryRunner} from "typeorm";

export class setting1638239388705 implements MigrationInterface {
    name = 'setting1638239388705'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "setting" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "key" character varying NOT NULL, "value" json NOT NULL, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1c4c95d773004250c157a744d6e" UNIQUE ("key"), CONSTRAINT "PK_fcb21187dc6094e24a48f677bed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1c4c95d773004250c157a744d6" ON "setting" ("key") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_1c4c95d773004250c157a744d6"`);
        await queryRunner.query(`DROP TABLE "setting"`);
    }

}
