name: Test Renovate App
on:
  pull_request:
    branches:
      - 'renovate/**'
    paths:
      - 'graphql-app/**'
      - '.github/workflows/test-renovate-app.yml'
env:
  CI: true
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
jobs:
  test:
    name: Test integrated app
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        apps: [ main, cron-pub ]
    env:
      APP_NAME: ${{ matrix.apps }}
      NODE_ENV: production
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: v18
      - working-directory: ./graphql-app
        run: npm ci --include=dev
      - working-directory: ./graphql-app
        run: npm run build --if-present